### PR TITLE
Issue#21 fix register account

### LINKED ISSUE #21: Register Account is broken
I get this error when trying to register for an account.
ApiKey

### PR DESCRIPTION
**Pull request by DillonStricklett**

### CODE REVIEW

File: Models/IdentityHelper.cs [hunk 1]
```diff
@@ -13,6 +13,7 @@ internal static void SetIdentityOptions(IdentityOptions options)
 		{
 			// Sign in options
 			options.SignIn.RequireConfirmedEmail = false;
+			options.SignIn.RequireConfirmedAccount = true;
```
Comment (MatthewVandyke) [inline Models/IdentityHelper.cs:16]: Are these different? Does the confirmed account broadly cover phone and email?

Comment (DillonStricklett) [reply Models/IdentityHelper.cs:16]: I  looked at the documentation and it says that the RequireConfirmedAccount checks to see if the account has been verified and the RequireConfirmedEmail checks to see if only the email is verified. So I am pretty sure that RequiredConfirmedAccount makes sure authentication has been done at least once in the multiple ways that verification can be completed, but the email just checks to see if email is verified.
